### ISSUE TITLE
Two player option (Game entering mode)

### ISSUE THREAD

**Issue by ghost** [sakya/corechess#19]
I'd love a two player option and not against an engine, so I could replay some games for reference.

Edit: This is not really necessary of course. I get that CoreChess is aiming to be a GUI for engines.

**Comment by thanhminhmr** [comment]
Also a mode for Engine vs Engine. This, in the other hand, should be a feature since CoreChess is a GUI for engines.

**Comment by sakya** [comment]
Do you think something like this would work?
![immagine](https://github.com/sakya/corechess/assets/289552/1e304538-fe5b-4ff3-816c-bf88804c1f12)
