### ISSUE TITLE
PGN export in latest git version

### ISSUE THREAD

**Issue by ghost** [sakya/corechess#23]
Here's the PGN file exported.

[Event "Casual Game"]
[Site "?"]
[Date "2022.07.12"]
[Round "?"]
[White "Bahri"]
[Black "Stockfish"]
[Result "*"]
[TimeControl "900"]
[SetUp "0"]
[WhitePlayerType "ChessLib.HumanPlayer"]
[WhiteTimeLeftMilliSecs "900000"]
[BlackPlayerType "ChessLib.EnginePlayer"]
[BlackEngine "{"$type":"ChessLib.Engines.Uci, ChessLib","Name":"Stockfish","Command":"/app/bin/Engines/stockfish/stockfish","WorkingDir":"/app/bin/Engines/stockfish","Author":"the Stockfish developers (see AUTHORS file)","PlayAs":1,"Options":[{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"Debug Log File","Value":"","Type":"string","Default":"","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"Threads","Value":"1","Type":"spin","Default":"1","Min":"1","Max":"512","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"Hash","Value":"16","Type":"spin","Default":"16","Min":"1","Max":"33554432","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"Ponder","Value":"true","Type":"check","Default":"false","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"MultiPV","Value":"1","Type":"spin","Default":"1","Min":"1","Max":"500","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"Skill Level","Value":"20","Type":"spin","Default":"20","Min":"0","Max":"20","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"Move Overhead","Value":"10","Type":"spin","Default":"10","Min":"0","Max":"5000","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"Slow Mover","Value":"100","Type":"spin","Default":"100","Min":"10","Max":"1000","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"nodestime","Value":"0","Type":"spin","Default":"0","Min":"0","Max":"10000","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"UCI_Chess960","Value":"false","Type":"check","Default":"false","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"UCI_AnalyseMode","Value":"false","Type":"check","Default":"false","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"UCI_LimitStrength","Value":"false","Type":"check","Default":"false","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"UCI_Elo","Value":"1350","Type":"spin","Default":"1350","Min":"1350","Max":"2850","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"UCI_ShowWDL","Value":"false","Type":"check","Default":"false","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"SyzygyPath","Value":"<empty>","Type":"string","Default":"<empty>","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"SyzygyProbeDepth","Value":"1","Type":"spin","Default":"1","Min":"1","Max":"100","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"Syzygy50MoveRule","Value":"true","Type":"check","Default":"true","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"SyzygyProbeLimit","Value":"7","Type":"spin","Default":"7","Min":"0","Max":"7","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"Use NNUE","Value":"true","Type":"check","Default":"true","ValidValues":[],"Internal":false},{"$type":"ChessLib.Engines.EngineBase+Option, ChessLib","Name":"EvalFile","Value":"nn-6877cd24400e.nnue","Type":"string","Default":"nn-6877cd24400e.nnue","ValidValues":[],"Internal":false}],"Id":"1f30ceb579914f5c9c8c6b361bd9838e"}"]
[BlackTimeLeftMilliSecs "899800"]

1. e4 {!!} d6

**Comment by sakya** [comment]
No problem, many thanks for the help
