### ISSUE TITLE
"Preview" popup doesn't show up on some moves

### ISSUE THREAD

**Issue by ghost** [sakya/corechess#24]
Hello,

I don't know what you call them, but the preview windows that popup when hovered over moves don't show up on some moves. Especially on the ones further down the Notation pane.

I don't know if it's related, but I use the game window at a different size than the default and this issue is in latest git version.

**Comment by sakya** [comment]
It's a known problem of Avalonia. The popup doesn't show up when it cannot be fully rendered inside the screen (i.e position + popup height > screen,height)
