### ISSUE TITLE
Just kudos!

### ISSUE THREAD

**Issue by kenpchess** [sakya/corechess#40]
I second everyone's kudos and suggestions. This is a beautiful app! After some huffing and puffing, I was able to build and run it on my 2018 mac mini (running macOS Big Sur 11.7.2). (On the mac it needs Visual Studio 2022 and dotnet SDK v7.0). Beautiful, simplistic, yet aesthetically pleasing to the eye! Very nice features. To the author, keep  developing the app please! See outskirts chess forum for some discussion of this app (http://outskirts.altervista.org/forum/viewtopic.php?t=3323) - kenpchess

**Comment by sakya** [comment]
Many thanks!
To build on macOS you shouldn't need Visual Studio.

This command should build the release in ./dist/osx-x64
`dotnet publish CoreChess.sln -c Release --runtime osx-x64 -p:PublishReadyToRun=true --self-contained --output ./dist/osx-x64`

I cannot test it, but it should work.
