### ISSUE TITLE
shutdown problem

### ISSUE THREAD

**Issue by Batu-64** [sakya/corechess#41]
I tested version 0.17.0.0 on Windows 7 and 10. Both have this problem:
After choosing File/New game/Ok it closes the program!

**Comment by sakya** [comment]
Did you install the program using the installer? Was it a fresh install or an update?

Can you please share the content of the file `C:\Users\USERNAME\AppData\Local\CoreChess\crash.log`?

**Comment by sakya** [comment]
Fixed, update to version 0.17.1, thanks
