### ISSUE TITLE
CoreChess crashed and unstartable after changing view option

### ISSUE THREAD

**Issue by CodeBiene** [sakya/corechess#45]
Hi!

After trying one of the 5 or 6 options in the "View" menu CoreChess crashed.
Since then it don't start anymore.
Attached the C:\Users\peter\AppData\Local\CoreChess\crash.log
[crash.log](https://github.com/user-attachments/files/16009203/crash.log)
I'm going to reinstall it now.

Kind regards,
Peter

**Comment by CodeBiene** [comment]
Once again CoreChess crashed and it's again unstartable.
To be honest I don't know what I did to produce this crash.
Beside the timestamp the new crash.log file (attached) is identical to the previous one.
[crash.log](https://github.com/user-attachments/files/16011282/crash.log)

Kind regards,
Peter

**Comment by sakya** [comment]
Ok, got it. Many thanks
This will be fixed in the next release
